### ISSUE TITLE
Getting "No content to map due to end-of-input"

### ISSUE THREAD

**Issue by fperreaultnv** [svt/encore#22]
**Describe the bug**
Trying to test the software in local environment with docker on windows

**To Reproduce**
- Copy this `docker-compose.yml` to a bare directory :

```
version: "3.7"

services:
  redis:
    image: redis:alpine
    networks:
      - encorenet
  encore:
    image: ghcr.io/svt/encore-debian:latest
    depends_on:
      - redis
    environment:
      - SPRING_PROFILES_ACTIVE=local
      - SPRING_REDIS_HOST=redis
      - PROFILE_LOCATION=url:https://raw.githubusercontent.com/svt/encore-doc/main/src/docs/asciidoc/examples/profile/profiles.yml
    ports:
      - 8080:8080
    volumes:
      - ./tmp/input:/tmp/input:rw # where your put your source files
      - ./tmp/output:/tmp/output:rw #put your output here
    networks:
      - encorenet

networks:
  encorenet:
    driver: bridge
```

- run `docker compose up`
- copy an `.mp4` file in `/tmp/input` directory
- queue a job targetting this `.mp4`

**Actual behavior**
I get this stack trace

```
[+] Running 2/0
 ✔ Container asmbl-transcoding-redis-1   Created                                                                                                                                                                       0.0s 
 ✔ Container asmbl-transcoding-encore-1  Recreated                                                                                                                                                                     0.0s 
Attaching to encore-1, redis-1
redis-1   | 1:C 19 Jan 2024 17:35:12.170 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
redis-1   | 1:C 19 Jan 2024 17:35:12.170 * oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis-1   | 1:C 19 Jan 2024 17:35:12.170 * Redis version=7.2.4, bits=64, commit=00000000, modified=0, pid=1, just started
redis-1   | 1:C 19 Jan 2024 17:35:12.170 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
redis-1   | 1:M 19 Jan 2024 17:35:12.171 * monotonic clock: POSIX clock_gettime
redis-1   | 1:M 19 Jan 2024 17:35:12.172 * Running mode=standalone, port=6379.
redis-1   | 1:M 19 Jan 2024 17:35:12.173 * Server initialized
redis-1   | 1:M 19 Jan 2024 17:35:12.173 * Loading RDB produced by version 7.2.4
redis-1   | 1:M 19 Jan 2024 17:35:12.173 * RDB age 15 seconds
redis-1   | 1:M 19 Jan 2024 17:35:12.173 * RDB memory usage when created 1.52 Mb
redis-1   | 1:M 19 Jan 2024 17:35:12.174 * Done loading RDB, keys loaded: 95, keys expired: 0.
redis-1   | 1:M 19 Jan 2024 17:35:12.174 * DB loaded from disk: 0.001 seconds
redis-1   | 1:M 19 Jan 2024 17:35:12.174 * Ready to accept connections tcp
encore-1  |                                                           ```````
encore-1  |                                                 ``.--:/+ossssyysssoo+/:-.```
encore-1  |                                            ``-:/syhdmmNNNMMMMMMMMMNNNNmddyso:-.`
encore-1  |                                         `.:oydmNMMMMMMNNNmmmmmmmmNNNMMMMMMMNmdho/-.-+/-
encore-1  |                                      `-/ydNNMMMNNmdyso//:--.....--::++oyhmmNMMMNNmmmNy+
encore-1  |                                   `-:ydNMMMNmdyo:-.```               ```.-/+yhmMMMMMMho
encore-1  |                                 `.ohmMMMNmho/-``                            ./hNMMMMMds
encore-1  |                               `-ohNMMMmd+:.`                                .:shdddmmhs`
encore-1  |                              -+dNMMNmo/.`                                    ``...--:-.
encore-1  |                            `-ydMMMms+``              `...-:/:.
encore-1  |                           .+dNMMmd:.               `-ohhdmmNhs        `.-``
encore-1  |                         `.ydMMNd+:                 ./dMMMMMMNd..`   `.shdy+:``               .-/:-
encore-1  |                         -oNMMNd/.                  `/hNMMMMMMMhyso+/osNMMMNms+.             `ohNdh-`
encore-1  |                        -omMMMy+`         `.--`   `.+smMMMMMMMMMMMNNNNMMMMMMMNh+`            `sdMMNs/`
encore-1  |                       `sdMMNd:`         `:ydds+:/shNNMMMMMMMMNNMMMMMMMMMMMMMho.              :oNMMNs:
encore-1  |                      .:mNMNh/`         `ohNMMMNmNNMMMMNmdhyo+++ooyhmNMMMMMMMs/               `-hmMMdy`
encore-1  |                      :oMMMdo.         -+mNMMMMMMMMMMmdo/..``` ````.-oymNMMMMds-`              `/hNMNm-.
encore-1  |                     `ohMMMo:          -smNMMMMMMMMNs+.               `:sdMMMMNh:-..-.`         `odMMMo:
encore-1  |                    `-yNMMN:.          ``/odNMMMMNho``   `.-++o++/.`    .-dmMMMMmdhddh+.         /yMMMy+
encore-1  |                    `/hMMNd.`             -yNMMMMh+.   `-ohmNNNNNmhs:`    /yNMMMMMMMMNy/         -+MMMdo`
encore-1  |                    `+dMMmy`             `:hNMMMN/-    +yNMMMMMMMMMNd/.   `+hMMMMMMMMMhs         .:NMMms-
encore-1  |                    `omMMds`            `-+mMMMMN-.  `-hmMMMMMMMMMMMMho    -oMMMMMMMMNdy`        `-NNMNy-`
encore-1  |                    .smMMds`        `.++ohdMMMMNm-`  `:dNMMMMMMMMMMMMds    -+NMMMMmhso/:         `-NNMNy-`
encore-1  |                    .smMMds`        -/NNMMMMMMMMN-.  `-hmMMMMMMMMMMMMho    :oMMMMms-``           .-NNMNy-`
encore-1  |                    `odMMmy`        .-mNMMMMMMMMM+-    +yNMMMMMMMMMNd/.   `+dMMMMd/`             ./NMMms-`
encore-1  |                    `/dMMNd.`       ``hmMMMMMMMMMd+.   `-ohmNNNNNmhs:`   `/yNMMMNh-`             :oMMMdo.
encore-1  |                    `-yNMNN:.         oymdddmNMMMMds.`   `.-++o++/.`    .:dNMMMMNms:.            /yMMMy+
encore-1  |                     .odMMMo:         ..--..+sNMMMMNy+.`      `       `:ydMMMMMMMMNmh-`         .sdMMMo:
encore-1  |                      /sMMMdo.              `.sdMMMMMNdo+-.```````.-:oyNNMMMMMMMMMMmy.`        `/hNMNm-.
encore-1  |                      .:mNMNh/`              `-ymMMMMMMNNdhyssossyhdmNMMMMMNmNNMMNm+-         `-hmMMdy`
encore-1  |                       `ydMMNd-`             `+hNMMMMMMMMMMMMMMMMMMMMMMMNms+/osddh/.          :oNMMms:
encore-1  |                        -smMMNo:            `:dNMMMMMMMNNNNMMMMMMMMMMMNy+:`` ``--.`         `-ymMMNs:`
encore-1  |                         -+mmm+:            `.+ydNMMMNdo++osydmMMMMMMMm/.                  `:yNMMmh-`
encore-1  |                         ``:::.`               .-oydds:`  ```/oMMMMMMMm+.                ``ohNMMNs/
encore-1  |                                                  .--.       .:NNNmmdhy:.               .:sNMMNm+-`
encore-1  |                                      `                       `///:-..`               .-ydNMMNs+`
encore-1  |                                    .:+//:::--`                                    `./sdMMMNdo-`
encore-1  |                                    /yNNNNNNdy.`                                `.:oyNNMMNmo:`
encore-1  |                                    :sMMMMMMds-.`                            `.:oymNMMMNho:`
encore-1  |                                    :+MMMMMMNNdys/:.```                ``.-/+yhmNMMMNdyo.`
encore-1  |                                    -/mdyhdNNMMMNNmdys+//:---------::/+oyhmmNMMMNNdyo-.`
encore-1  |                                    `.:-``./oydmNMMMMMMMNNmmmmmmmmmNNMMMMMMNNmdyo/.`
encore-1  |                                            ``-:/syhddmNNNNMMMMMMMNNNNmdhhso+:-`
encore-1  |                                                 ``.--:/++oossyysso++/:-..``
encore-1  |
encore-1  |
encore-1  | 2024-01-19 17:35:13.399  INFO 1 --- [           main] s.s.o.e.EncoreApplicationKt              : Starting EncoreApplicationKt using Java 11.0.15 on c8a3f22bd829 with PID 1 (/app/encore.jar started by avtools in /app)
encore-1  | 2024-01-19 17:35:13.403  INFO 1 --- [           main] s.s.o.e.EncoreApplicationKt              : The following 1 profile is active: "local"
encore-1  | 2024-01-19 17:35:13.939  INFO 1 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Multiple Spring Data modules found, entering strict repository configuration mode
encore-1  | 2024-01-19 17:35:13.939  INFO 1 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data Redis repositories in DEFAULT mode.
encore-1  | 2024-01-19 17:35:14.112  INFO 1 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 166 ms. Found 1 Redis repository interfaces.
encore-1  | 2024-01-19 17:35:14.516  INFO 1 --- [           main] o.s.c.c.s.GenericScope                   : BeanFactory id=57e93272-a9ba-3687-a66c-dc857193e26a
encore-1  | 2024-01-19 17:35:14.602  INFO 1 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.retry.annotation.RetryConfiguration' of type [org.springframework.retry.annotation.RetryConfiguration] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
encore-1  | 2024-01-19 17:35:14.828  INFO 1 --- [           main] o.s.b.w.e.t.TomcatWebServer              : Tomcat initialized with port(s): 8080 (http)
encore-1  | 2024-01-19 17:35:14.836  INFO 1 --- [           main] o.a.c.c.StandardService                  : Starting service [Tomcat]
encore-1  | 2024-01-19 17:35:14.837  INFO 1 --- [           main] o.a.c.c.StandardEngine                   : Starting Servlet engine: [Apache Tomcat/9.0.69]
encore-1  | 2024-01-19 17:35:14.889  INFO 1 --- [           main] o.a.c.c.C.[.[.[/]                        : Initializing Spring embedded WebApplicationContext
encore-1  | 2024-01-19 17:35:14.890  INFO 1 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 1440 ms
encore-1  | 2024-01-19 17:35:15.517  INFO 1 --- [           main] o.r.Version                              : Redisson 3.18.1
encore-1  | 2024-01-19 17:35:15.717  INFO 1 --- [isson-netty-2-6] o.r.c.p.MasterPubSubConnectionPool       : 1 connections initialized for redis/172.18.0.2:6379
encore-1  | 2024-01-19 17:35:15.817  INFO 1 --- [sson-netty-2-19] o.r.c.p.MasterConnectionPool             : 24 connections initialized for redis/172.18.0.2:6379
encore-1  | WARNING: An illegal reflective access operation has occurred
encore-1  | WARNING: Illegal reflective access by org.springframework.util.ReflectionUtils (jar:file:/app/encore.jar!/BOOT-INF/lib/spring-core-5.3.24.jar!/) to constructor java.net.URI()
encore-1  | WARNING: Please consider reporting this to the maintainers of org.springframework.util.ReflectionUtils
encore-1  | WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
encore-1  | WARNING: All illegal access operations will be denied in a future release
encore-1  | 2024-01-19 17:35:16.329  INFO 1 --- [           main] o.s.c.o.FeignClientFactoryBean           : For 'callback' URL not provided. Will try picking an instance via load-balancing.
encore-1  | 2024-01-19 17:35:18.053  INFO 1 --- [           main] o.s.b.a.e.w.EndpointLinksResolver        : Exposing 1 endpoint(s) beneath base path ''
encore-1  | 2024-01-19 17:35:18.094  INFO 1 --- [           main] o.s.b.w.e.t.TomcatWebServer              : Tomcat started on port(s): 8080 (http) with context path ''
encore-1  | 2024-01-19 17:35:18.111  INFO 1 --- [           main] s.s.o.e.EncoreApplicationKt              : Started EncoreApplicationKt in 5.06 seconds (JVM running for 5.664)
encore-1  | 2024-01-19 17:36:53.655  INFO 1 --- [nio-8080-exec-1] o.a.c.c.C.[.[.[/]                        : Initializing Spring DispatcherServlet 'dispatcherServlet'
encore-1  | 2024-01-19 17:36:53.655  INFO 1 --- [nio-8080-exec-1] o.s.w.s.DispatcherServlet                : Initializing Servlet 'dispatcherServlet'
encore-1  | 2024-01-19 17:36:53.656  INFO 1 --- [nio-8080-exec-1] o.s.w.s.DispatcherServlet                : Completed initialization in 1 ms
encore-1  | 2024-01-19 17:36:53.980  INFO 1 --- [nio-8080-exec-1] s.s.o.e.h.EncoreJobHandler               : Adding job to queue.. EncoreJob(id=14bf1419-c55a-4c74-9c1f-9c59c99ddc12, externalId=any-string, profile=X264Encode, outputFolder=/output, baseName=any_file, createdDate=2024-01-19T17:36:53.834179Z, progressCallbackUri=null, priority=0, message=null, progress=0, speed=null, startedDate=null, completedDate=null, debugOverlay=false, logContext={}, seekTo=null, duration=null, thumbnailTime=null, inputs=[AudioInput(uri=/tmp/input/Interesting.mp4, audioLabel=main, params={ac=2}, audioFilters=[], analyzed=null, audioStream=null, channelLayout=null, seekTo=null)])
encore-1  | 2024-01-19 17:36:53.999  INFO 1 --- [nio-8080-exec-1] s.s.o.e.h.EncoreJobHandler               : Added job to queue
encore-1  | 2024-01-19 17:36:57.674  INFO 1 --- [   scheduling-3] s.s.o.e.s.p.JobPoller                    : Handling job 14bf1419-c55a-4c74-9c1f-9c59c99ddc12
encore-1  | 2024-01-19 17:36:57.683  INFO 1 --- [   scheduling-3] s.s.o.e.s.p.JobPoller                    : Running job
encore-1  | 2024-01-19 17:36:57.783 ERROR 1 --- [   scheduling-3] s.s.o.e.s.EncoreService                  : Job execution failed: Error parsing ProbeResult from output: ''
encore-1  |
encore-1  | java.lang.RuntimeException: Error parsing ProbeResult from output: ''
encore-1  |     at se.svt.oss.mediaanalyzer.ffprobe.FfprobeAnalyzer.analyze(FfprobeAnalyzer.kt:73) ~[media-analyzer-2.0.1.jar!/:?]
encore-1  |     at se.svt.oss.mediaanalyzer.MediaAnalyzer.analyze(MediaAnalyzer.kt:60) ~[media-analyzer-2.0.1.jar!/:?]
encore-1  |     at se.svt.oss.encore.service.mediaanalyzer.MediaAnalyzerService.analyzeInput(MediaAnalyzerService.kt:29) ~[classes!/:?]
encore-1  |     at se.svt.oss.encore.service.EncoreService.encode(EncoreService.kt:72) ~[classes!/:?]
encore-1  |     at se.svt.oss.encore.service.poll.JobPoller.handleJob(JobPoller.kt:77) ~[classes!/:?]
encore-1  |     at se.svt.oss.encore.service.poll.JobPoller.init$lambda$2$lambda$1(JobPoller.kt:47) ~[classes!/:?]
encore-1  |     at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-5.3.24.jar!/:5.3.24]
encore-1  |     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
encore-1  |     at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[?:?]
encore-1  |     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
encore-1  |     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
encore-1  |     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
encore-1  |     at java.lang.Thread.run(Thread.java:829) ~[?:?]
encore-1  | Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: No content to map due to end-of-input
encore-1  |  at [Source: (String)""; line: 1, column: 0]
encore-1  |     at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59) ~[jackson-databind-2.13.4.2.jar!/:2.13.4.2]
encore-1  |     at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4765) ~[jackson-databind-2.13.4.2.jar!/:2.13.4.2]
encore-1  |     at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4667) ~[jackson-databind-2.13.4.2.jar!/:2.13.4.2]
encore-1  |     at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3629) ~[jackson-databind-2.13.4.2.jar!/:2.13.4.2]
encore-1  |     at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3612) ~[jackson-databind-2.13.4.2.jar!/:2.13.4.2]
encore-1  |     at se.svt.oss.mediaanalyzer.ffprobe.FfprobeAnalyzer.analyze(FfprobeAnalyzer.kt:70) ~[media-analyzer-2.0.1.jar!/:?]
encore-1  |     ... 12 more
```

**Expected behavior**
Expected the video to be transcoded to the output folder

**Desktop (please complete the following information):**
 - OS: Windows 11

**Additional context**
Any help with this error is greatly appreciated!

**Comment by jd7352** [comment]
I also encountered the same problem, as encore did not update the document and I am currently unsure where to troubleshoot. I hope to receive help.

**Comment by dtoerber** [comment]
I am seeing this same issue following the SVT Encore Documentation.

OS: MacOS 14.5
