### ISSUE TITLE
Connection Refused messages

### ISSUE THREAD

**Issue by ajohnson-512** [svt/encore#9]
Hello,

I'm encountering an issue with getting a Connection Refused message when starting a job within Encore.  

The instance seems to start without issue, the only warning being for 'org.springframework.retry.annotation.RetryConfiguration'.  I'm able to submit the following curl POST:

```
curl -X 'POST' \
  'http://localhost:8080/encoreJobs' \
  -H 'accept: application/hal+json' \
  -H 'Content-Type: application/json' \
  -d '{
  "externalId": "testing",
  "profile": "480p",
  "outputFolder": "/home/tux/files/transcoded",
  "baseName": "test123",
  "priority": 0,
  "debugOverlay": false,
  "logContext": {},
  "seekTo": 0,
  "thumbnailTime": 1,
  "inputs": [
    {
      "type": "AudioVideo",
      "params": {
        "ac": "2"
      },
      "uri": "/home/tux/files/Brugge-Oostende.mp4"
    }
  ]
}'
```

I see the job fire, the file gets evaluated (viewable in the swagger api), however after the job start this output presents itself:

> 2021-11-11 23:35:15.610  INFO 782278 --- [   scheduling-2] s.s.o.e.s.EncoreService                  : Start EncoreJob(id=4b068fe4-93c8-4804-8da5-93a815bf4286, externalId=testing, profile=480p, outputFolder=/home/tux/files/transcoded, baseName=test123, createdDate=2021-11-11T23:35:04.821030Z, progressCallbackUri=null, priority=0, message=null, progress=0, speed=null, startedDate=null, completedDate=null, debugOverlay=false, logContext={}, seekTo=0.0, duration=null, thumbnailTime=1.0, inputs=[AudioVideoInput(uri=/home/tux/files/Brugge-Oostende.mp4, videoLabel=main, audioLabel=main, params={ac=2}, dar=null, useFirstAudioStreams=null, cropTo=null, padTo=null, videoFilters=[], audioFilters=[], analyzed=VideoFile(file=/home/tux/files/Brugge-Oostende.mp4, fileSize=14881064994, format=MPEG-4, overallBitrate=22079196, duration=5391.8865, videoStreams=[VideoStream(format=AVC, codec=h264, profile=High, level=5.1, width=3840, height=2160, sampleAspectRatio=1:1, displayAspectRatio=16:9, pixelFormat=yuv420p, frameRate=30000/1001, duration=5391.8865, bitrate=21979623, bitDepth=8, numFrames=161595, isInterlaced=false, transferCharacteristics=BT.709)], audioStreams=[AudioStream(format=AAC, codec=aac, duration=5391.8865, channels=2, samplingRate=48000, bitrate=95901)]), videoStream=null, audioStream=null, probeInterlaced=true)])
> 
> 2021-11-11 23:35:17.720 ERROR 782278 --- [   scheduling-2] s.s.o.e.s.EncoreService                  : Job execution failed: Connection refused (Connection refused)
> 
> java.net.ConnectException: Connection refused (Connection refused)

Is this related to a profile issue? I have the pointer to it in the config as 

```
profile:
    location: classpath:profile.yml
```    

Which contains the profile name and reference to the yml with the encoding details.  

Can you shed any light as to what the service is trying to connect to? I've tried this with no firewall and the message has been the same. 

Thanks in advance.

**Comment by guacharo** [comment]
Running the app with the extra --scan doesn't provide any additional insights.

$ SPRING_PROFILES_ACTIVE=local ./gradlew clean bootRun  --scan

> Task :bootRun
                                                          ```````
                                                ``.--:/+ossssyysssoo+/:-.```
                                           ``-:/syhdmmNNNMMMMMMMMMNNNNmddyso:-.`
                                        `.:oydmNMMMMMMNNNmmmmmmmmNNNMMMMMMMNmdho/-.-+/-
                                     `-/ydNNMMMNNmdyso//:--.....--::++oyhmmNMMMNNmmmNy+
                                  `-:ydNMMMNmdyo:-.```               ```.-/+yhmMMMMMMho
                                `.ohmMMMNmho/-``                            ./hNMMMMMds
                              `-ohNMMMmd+:.`                                .:shdddmmhs`
                             -+dNMMNmo/.`                                    ``...--:-.
                           `-ydMMMms+``              `...-:/:.
                          .+dNMMmd:.               `-ohhdmmNhs        `.-``
                        `.ydMMNd+:                 ./dMMMMMMNd..`   `.shdy+:``               .-/:-
                        -oNMMNd/.                  `/hNMMMMMMMhyso+/osNMMMNms+.             `ohNdh-`
                       -omMMMy+`         `.--`   `.+smMMMMMMMMMMMNNNNMMMMMMMNh+`            `sdMMNs/`
                      `sdMMNd:`         `:ydds+:/shNNMMMMMMMMNNMMMMMMMMMMMMMho.              :oNMMNs:
                     .:mNMNh/`         `ohNMMMNmNNMMMMNmdhyo+++ooyhmNMMMMMMMs/               `-hmMMdy`
                     :oMMMdo.         -+mNMMMMMMMMMMmdo/..``` ````.-oymNMMMMds-`              `/hNMNm-.
                    `ohMMMo:          -smNMMMMMMMMNs+.               `:sdMMMMNh:-..-.`         `odMMMo:
                   `-yNMMN:.          ``/odNMMMMNho``   `.-++o++/.`    .-dmMMMMmdhddh+.         /yMMMy+
                   `/hMMNd.`             -yNMMMMh+.   `-ohmNNNNNmhs:`    /yNMMMMMMMMNy/         -+MMMdo`
                   `+dMMmy`             `:hNMMMN/-    +yNMMMMMMMMMNd/.   `+hMMMMMMMMMhs         .:NMMms-
                   `omMMds`            `-+mMMMMN-.  `-hmMMMMMMMMMMMMho    -oMMMMMMMMNdy`        `-NNMNy-`
                   .smMMds`        `.++ohdMMMMNm-`  `:dNMMMMMMMMMMMMds    -+NMMMMmhso/:         `-NNMNy-`
                   .smMMds`        -/NNMMMMMMMMN-.  `-hmMMMMMMMMMMMMho    :oMMMMms-``           .-NNMNy-`
                   `odMMmy`        .-mNMMMMMMMMM+-    +yNMMMMMMMMMNd/.   `+dMMMMd/`             ./NMMms-`
                   `/dMMNd.`       ``hmMMMMMMMMMd+.   `-ohmNNNNNmhs:`   `/yNMMMNh-`             :oMMMdo.
                   `-yNMNN:.         oymdddmNMMMMds.`   `.-++o++/.`    .:dNMMMMNms:.            /yMMMy+
                    .odMMMo:         ..--..+sNMMMMNy+.`      `       `:ydMMMMMMMMNmh-`         .sdMMMo:
                     /sMMMdo.              `.sdMMMMMNdo+-.```````.-:oyNNMMMMMMMMMMmy.`        `/hNMNm-.
                     .:mNMNh/`              `-ymMMMMMMNNdhyssossyhdmNMMMMMNmNNMMNm+-         `-hmMMdy`
                      `ydMMNd-`             `+hNMMMMMMMMMMMMMMMMMMMMMMMNms+/osddh/.          :oNMMms:
                       -smMMNo:            `:dNMMMMMMMNNNNMMMMMMMMMMMNy+:`` ``--.`         `-ymMMNs:`
                        -+mmm+:            `.+ydNMMMNdo++osydmMMMMMMMm/.                  `:yNMMmh-`
                        ``:::.`               .-oydds:`  ```/oMMMMMMMm+.                ``ohNMMNs/
                                                 .--.       .:NNNmmdhy:.               .:sNMMNm+-`
                                     `                       `///:-..`               .-ydNMMNs+`
                                   .:+//:::--`                                    `./sdMMMNdo-`
                                   /yNNNNNNdy.`                                `.:oyNNMMNmo:`
                                   :sMMMMMMds-.`                            `.:oymNMMMNho:`
                                   :+MMMMMMNNdys/:.```                ``.-/+yhmNMMMNdyo.`
                                   -/mdyhdNNMMMNNmdys+//:---------::/+oyhmmNMMMNNdyo-.`
                                   `.:-``./oydmNMMMMMMMNNmmmmmmmmmNNMMMMMMNNmdyo/.`
                                           ``-:/syhddmNNNNMMMMMMMNNNNmdhhso+:-`
                                                ``.--:/++oossyysso++/:-..``


2021-11-15 22:03:40.409  INFO 1123298 --- [           main] s.s.o.e.EncoreApplicationKt              : Starting EncoreApplicationKt using Java 11.0.11 on vm1296 with PID 1123298 (/home/tux/encore/build/classes/kotlin/main started by tux in /home/tux/encore)
2021-11-15 22:03:40.421  INFO 1123298 --- [           main] s.s.o.e.EncoreApplicationKt              : The following profiles are active: local
2021-11-15 22:03:41.845  INFO 1123298 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Multiple Spring Data modules found, entering strict repository configuration mode!
2021-11-15 22:03:41.846  INFO 1123298 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data Redis repositories in DEFAULT mode.
2021-11-15 22:03:42.014  INFO 1123298 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 152 ms. Found 1 Redis repository interfaces.
2021-11-15 22:03:42.952  INFO 1123298 --- [           main] o.s.c.c.s.GenericScope                   : BeanFactory id=88fdf73a-d390-3f90-805f-383d5badcb7c
2021-11-15 22:03:43.092  INFO 1123298 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.retry.annotation.RetryConfiguration' of type [org.springframework.retry.annotation.RetryConfiguration] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2021-11-15 22:03:43.558  INFO 1123298 --- [           main] o.s.b.w.e.t.TomcatWebServer              : Tomcat initialized with port(s): 8080 (http)
2021-11-15 22:03:43.571  INFO 1123298 --- [           main] o.a.c.c.StandardService                  : Starting service [Tomcat]
2021-11-15 22:03:43.572  INFO 1123298 --- [           main] o.a.c.c.StandardEngine                   : Starting Servlet engine: [Apache Tomcat/9.0.52]
2021-11-15 22:03:43.739  INFO 1123298 --- [           main] o.a.c.c.C.[.[.[/]                        : Initializing Spring embedded WebApplicationContext
2021-11-15 22:03:43.739  INFO 1123298 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 3216 ms
2021-11-15 22:03:44.670  INFO 1123298 --- [           main] o.r.Version                              : Redisson 3.16.2
2021-11-15 22:03:45.038  INFO 1123298 --- [sson-netty-2-23] o.r.c.p.MasterPubSubConnectionPool       : 1 connections initialized for localhost/127.0.0.1:6379
2021-11-15 22:03:45.081  INFO 1123298 --- [sson-netty-2-20] o.r.c.p.MasterConnectionPool             : 24 connections initialized for localhost/127.0.0.1:6379
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.springframework.util.ReflectionUtils (file:/home/tux/.gradle/caches/modules-2/files-2.1/org.springframework/spring-core/5.3.9/cfef19d1dfa41d56f8de66238dc015334997d573/spring-core-5.3.9.jar) to constructor java.net.URI()
WARNING: Please consider reporting this to the maintainers of org.springframework.util.ReflectionUtils
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
2021-11-15 22:03:46.349  WARN 1123298 --- [           main] o.s.c.o.FeignClientFactoryBean           : The provided URL is empty. Will try picking an instance via load-balancing.
2021-11-15 22:03:49.480  INFO 1123298 --- [           main] o.s.b.a.e.w.EndpointLinksResolver        : Exposing 1 endpoint(s) beneath base path ''
2021-11-15 22:03:49.582  INFO 1123298 --- [           main] o.s.b.w.e.t.TomcatWebServer              : Tomcat started on port(s): 8080 (http) with context path ''
2021-11-15 22:03:49.615  INFO 1123298 --- [           main] s.s.o.e.EncoreApplicationKt              : Started EncoreApplicationKt in 10.069 seconds (JVM running for 11.309)
2021-11-15 22:23:58.596  INFO 1123298 --- [nio-8080-exec-1] o.a.c.c.C.[.[.[/]                        : Initializing Spring DispatcherServlet 'dispatcherServlet'
2021-11-15 22:23:58.597  INFO 1123298 --- [nio-8080-exec-1] o.s.w.s.DispatcherServlet                : Initializing Servlet 'dispatcherServlet'
2021-11-15 22:23:58.600  INFO 1123298 --- [nio-8080-exec-1] o.s.w.s.DispatcherServlet                : Completed initialization in 3 ms
2021-11-15 22:24:09.305  INFO 1123298 --- [nio-8080-exec-2] s.s.o.e.h.EncoreJobHandler               : Adding job to queue.. EncoreJob(id=97ea92b7-005b-47b6-8deb-01ca57538c9e, externalId=testing, profile=480p, outputFolder=/home/tux/files/transcoded, baseName=test123, createdDate=2021-11-15T22:24:08.817413Z, progressCallbackUri=null, priority=0, message=null, progress=0, speed=null, startedDate=null, completedDate=null, debugOverlay=false, logContext={}, seekTo=0.0, duration=null, thumbnailTime=1.0, inputs=[AudioVideoInput(uri=/home/tux/files/Brugge-Oostende.mp4, videoLabel=main, audioLabel=main, params={ac=2}, dar=null, useFirstAudioStreams=null, cropTo=null, padTo=null, videoFilters=[], audioFilters=[], analyzed=null, videoStream=null, audioStream=null, probeInterlaced=true)])
2021-11-15 22:24:09.322  INFO 1123298 --- [nio-8080-exec-2] s.s.o.e.h.EncoreJobHandler               : Added job to queue
2021-11-15 22:24:12.983  INFO 1123298 --- [   scheduling-2] s.s.o.e.s.p.JobPoller                    : Handling job 97ea92b7-005b-47b6-8deb-01ca57538c9e
2021-11-15 22:24:13.015  INFO 1123298 --- [   scheduling-2] s.s.o.e.s.p.JobPoller                    : Running job
2021-11-15 22:24:21.923  INFO 1123298 --- [   scheduling-2] s.s.o.e.s.EncoreService                  : Start EncoreJob(id=97ea92b7-005b-47b6-8deb-01ca57538c9e, externalId=testing, profile=480p, outputFolder=/home/tux/files/transcoded, baseName=test123, createdDate=2021-11-15T22:24:08.817413Z, progressCallbackUri=null, priority=0, message=null, progress=0, speed=null, startedDate=null, completedDate=null, debugOverlay=false, logContext={}, seekTo=0.0, duration=null, thumbnailTime=1.0, inputs=[AudioVideoInput(uri=/home/tux/files/Brugge-Oostende.mp4, videoLabel=main, audioLabel=main, params={ac=2}, dar=null, useFirstAudioStreams=null, cropTo=null, padTo=null, videoFilters=[], audioFilters=[], analyzed=VideoFile(file=/home/tux/files/Brugge-Oostende.mp4, fileSize=14881064994, format=MPEG-4, overallBitrate=22079196, duration=5391.8865, videoStreams=[VideoStream(format=AVC, codec=h264, profile=High, level=5.1, width=3840, height=2160, sampleAspectRatio=1:1, displayAspectRatio=16:9, pixelFormat=yuv420p, frameRate=30000/1001, duration=5391.8865, bitrate=21979623, bitDepth=8, numFrames=161595, isInterlaced=false, transferCharacteristics=BT.709)], audioStreams=[AudioStream(format=AAC, codec=aac, duration=5391.8865, channels=2, samplingRate=48000, bitrate=95901)]), videoStream=null, audioStream=null, probeInterlaced=true)])
2021-11-15 22:24:24.311 ERROR 1123298 --- [   scheduling-2] s.s.o.e.s.EncoreService                  : Job execution failed: Connection refused (Connection refused)

java.net.ConnectException: Connection refused (Connection refused)
        at java.net.PlainSocketImpl.socketConnect(Native Method) ~[?:?]
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399) ~[?:?]
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242) ~[?:?]
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224) ~[?:?]
        at java.net.Socket.connect(Socket.java:609) ~[?:?]
        at java.net.Socket.connect(Socket.java:558) ~[?:?]
        at sun.net.NetworkClient.doConnect(NetworkClient.java:182) ~[?:?]
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:474) ~[?:?]
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:569) ~[?:?]
        at sun.net.www.http.HttpClient.<init>(HttpClient.java:242) ~[?:?]
        at sun.net.www.http.HttpClient.New(HttpClient.java:341) ~[?:?]
        at sun.net.www.http.HttpClient.New(HttpClient.java:362) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1253) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1187) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1081) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1015) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1592) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520) ~[?:?]
        at org.springframework.core.io.UrlResource.getInputStream(UrlResource.java:186) ~[spring-core-5.3.9.jar:5.3.9]
        at se.svt.oss.encore.service.profile.ProfileService.getProfile(ProfileService.kt:47) ~[main/:?]
        at se.svt.oss.encore.service.profile.ProfileService$$FastClassBySpringCGLIB$$1ef4d098.invoke(<generated>) ~[main/:?]
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.9.jar:5.3.9]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:779) ~[spring-aop-5.3.9.jar:5.3.9]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.3.9.jar:5.3.9]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750) ~[spring-aop-5.3.9.jar:5.3.9]
        at org.springframework.retry.interceptor.RetryOperationsInterceptor$1.doWithRetry(RetryOperationsInterceptor.java:93) ~[spring-retry-1.3.1.jar:?]
        at org.springframework.retry.support.RetryTemplate.doExecute(RetryTemplate.java:329) ~[spring-retry-1.3.1.jar:?]
        at org.springframework.retry.support.RetryTemplate.execute(RetryTemplate.java:209) ~[spring-retry-1.3.1.jar:?]
        at org.springframework.retry.interceptor.RetryOperationsInterceptor.invoke(RetryOperationsInterceptor.java:119) ~[spring-retry-1.3.1.jar:?]
        at org.springframework.retry.annotation.AnnotationAwareRetryOperationsInterceptor.invoke(AnnotationAwareRetryOperationsInterceptor.java:163) ~[spring-retry-1.3.1.jar:?]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.9.jar:5.3.9]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750) ~[spring-aop-5.3.9.jar:5.3.9]
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:692) ~[spring-aop-5.3.9.jar:5.3.9]
        at se.svt.oss.encore.service.profile.ProfileService$$EnhancerBySpringCGLIB$$9c21579.getProfile(<generated>) ~[main/:?]
        at se.svt.oss.encore.service.EncoreService.encode(EncoreService.kt:79) ~[main/:?]
        at se.svt.oss.encore.service.poll.JobPoller.handleJob(JobPoller.kt:77) ~[main/:?]
        at se.svt.oss.encore.service.poll.JobPoller.init$lambda-2$lambda-1(JobPoller.kt:47) ~[main/:?]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-5.3.9.jar:5.3.9]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]

<===========--> 85% EXECUTING [22m 17s]
> :bootRun

**Comment by guacharo** [comment]
After a lot of troubleshooting I think I have this figured it out.

By default src/main/resources/application-local.yml contains:

service:
  name: encore-local

profile:
  location: url:http://localhost/profiles.yml

After each restart of the app with SPRING_PROFILES_ACTIVE=local ./gradlew clean bootRun
It looks like everything in src/main/resources/ gets reset.

So if we update src/main/resources/application-local.yml  to a valid file after the app starts, and before firing off a job, and ffmpeg process starts as expected.

The next question comes in terms of production level configs. What is the recommended way to:
- Run the application in production with authentication (and in the background).
 - Do you have a recommended procedure to add other nodes in production? Or is is this as simple as configuring redis to allow remote connections, compile svt encore, and point it to the same redis instance?

Thanks in advance.

**Comment by janderssonse** [comment]
Glad if you found the first problem. To answer the first part, yes, Resources from src/main/resources are copied to build/resources/main so any changes would have to take place in src/main/resources to work or they would be overwritten as bootRun src/main/resources is picked up. .See the config-list on how config properties are picked here. https://docs.spring.io/spring-boot/docs/current/reference/html/features.html#features.external-config. For example having another profile called application-customlocal.yml just in the root foolder and running  SPRING_PROFILES_ACTIVE=customlocal ./gradlew clean bootRun would pick up that profile instead. Also, note you should see which profile is being picked up in the terminal when starting.

![bild](https://user-images.githubusercontent.com/37870813/142189221-bcb5def3-f8a7-4378-8525-d0ba9e2d0405.png)

Note: the application-local.yml is just a testprofile with bare essentials to get started, and does not contain much.  

As for auth, there is only a basic auth support - which i notice now on the to-do list to add to to the documentation document -, and 2 default users setup ,but have a look in Integrationtest EncoreEndpointAccessIntegrationTest.kt for guidance on settings, and I'll try to update the documentation for this auth as soon as I have some spare time. 

As for production configuration, You will have to find what suits your environment and possibilities , but having a look in the documentation under User Guide, Creating a Dockerfile for easy scaling of encore-nodes, and thinking about if you are intending to setup Redis in single, cluster mode or maybe sentinel would be a great start. Depending on use case and environments of course. Yes,  Start small. Also have a look under Scaling, Distribution and queues in the documentation.

**Comment by janderssonse** [comment]
I guess we can close this, as the original question seems to have been solved.

**Comment by janderssonse** [comment]
Closing this, and hope the suggestions took you further.
